---
title: "Basic Tutorial"
author: "Dana Gibbon"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


# Quick start

* Install `PressPurtCoreAlg`

```{r install, eval=FALSE}
# Specify branch and build vignettes
devtools::install_github("dkoslicki/PressPurtCoreAlg", 
                         ref = "gibbond", build_vignettes = TRUE)
```

* Load the library
* Check available python versions
* Set python with previously made conda environment
* install python dependencies
* Run PreprocessMatrix
* Run ComputeEntryWisePerturbationExpectation
* Plot
    * specific figures
    * all figures

```{r quick_start_setup}
library(PressPurtCoreAlg)
find_python()
set_python("r-reticulate", verbose = TRUE)
```

```{r quick_start_install, eval=FALSE}
py_depend("r-reticulate")
```

```{r quick_start_run}
# Path to your matrix
infile <- system.file("extdata", "IGP.csv", package = "PressPurtCoreAlg")
PreProsMatrix <- PreprocessMatrix(input_file = infile, output_folder = NULL, max_bound = 10, threads = 2)
Entrywise <- ComputeEntryWisePerturbationExpectation(PreProsMatrix = PreProsMatrix, 
                                        distribution_type="truncnorm", 
                                        input_a=0, input_b=-2, threads=1)
list_of_numswitch_to_plot <- list(c(1, 1), c(1, 2))
GenerateEntryWiseFigures(EntryWise=Entrywise, 
                         all_numswitch_plots = FALSE, 
                         list_of_numswitch_to_plot=list_of_numswitch_to_plot)
```

```{r all_plots, fig.width=9, fig.height=8}
GenerateEntryWiseFigures(EntryWise=Entrywise, 
                         all_numswitch_plots = TRUE)
```
